version: 2
updates:
  - package-ecosystem: "pip"  # Para dependências Python
    directory: "/"            # Diretório onde o requirements.txt está
    schedule:
      interval: "daily"       # Verifica atualizações diariamente
    open-pull-requests-limit: 10  # Limita o número de PRs abertos simultaneamente
    labels:                   # Adiciona rótulos aos PRs
      - "dependencies"
      - "automated"
    ignore:                   # Ignora dependências específicas ou versões
      - dependency-name: "django"
        versions: ["2.2.*"]   # Ignora atualizações para Django 2.2.x
    commit-message:           # Personaliza a mensagem de commit
      prefix: "chore"
      include: "scope"
    automerge: true           # Habilita o merge automático
    automerge-strategy: "squash"  # Define a estratégia de merge (squash, merge, rebase)
