# Generated by Django 5.0.2 on 2024-03-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctor_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='HealthProfessional',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='health_professional',
        ),
    ]
